### ISSUE TITLE
Implement all data types in parameter editor

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-web-editor#43]
Related: #80, #39

General types:
- [x] null
- [x] string
- [x] number
- [x] integer
- [x] boolean
- [x] objects (see also #78)
- [x] arrays
  - [x] ToDo:  Subtype selection, see #75

Missing subtypes:
- [x] band-name (may depend on #26)
- [x] bounding-box
- [x] collection-id
- [x] date
- [x] date-time
- [x] epsg-code
- [x] file-path
- [x] file-paths (via arrays)
- [x] geojson
- [x] input-format
- [x] input-format-options
- [x] job-id (see also #42)
- [x] kernel (see #194)
- [x] ~labeled-array~ (these can't be sent to the server)
- [x] metadata-filter
- [x] output-format
- [x] output-format-options
- [x] process-graph
- [x] ~proj-definition~ (deprecated)
- [x] temporal-interval
  - [x] ToDo: missing support for open date ranges, probably by using two separate date pickers, see also https://github.com/chronotruck/vue-ctk-date-time-picker/issues/121)
- [x] temporal-intervals (via arrays)
- [x] time
- [x] udf-code
- [x] udf-runtime (see also #42)
- [x] udf-runtime-version (see also #42)
- [x] uri (url-textbox)
- [x] wkt2-definition

Other types:
- [x] Commonmark (textarea)
- [x] Service config, see #192
- [x] Budget
- [x] Result Node
- [x] Parameters
  - [x] ToDo: see also #39
- [x] Enum
- [x] Service type
- [x] Billing plan
- [x] Multiline text (textarea)

**Comment by slim01** [comment]
Regarding objects, there can be an editor similar to the array editor so the user don't have to write in json directly.
However, for having multiple results as input for objects, there some challenges:
The user has to specify in the editor where to use which result.
The plan for this at the moment is:

- The user inputs one result to an empty object -> the result will be used directly for the object.
- The user inputs more than one result OR one result to a non-empty object -> the user gets a notification and has to manually specify in the editor where to use which result. 

A problem with this is that the Visual mode does not exactly represent the json mode. A solution to this might be e.g. dotted arrows in case the input is not specified manually and therefore not in use.

**Comment by m-mohr** [comment]
The dashed arrow is a nice idea! 
Can be implemented easily by storing a flag for the Edge and the pass the SVG attribute stroke-dasharray to the SVG drawer in edge.js, line 77:
```
    svg.line(this.position1.x, this.position1.y, this.position2.x, this.position2.y, {
        'stroke': strokeStyle, 'stroke-width': lineWidth, 'stroke-dasharray': '4 2'
    });
```

**Comment by m-mohr** [comment]
Opened separate issues for the missing data types: #193, #194, #195
